import {WEAPONS} from './engine.js';
import {drawFlamethrower} from './flamethrower-art.js';
import {emptyFeaturePlan,seededFeaturePlan,requiredConnections} from './feature-plan.js';
import {layerCompositor} from './layers.js';
import {DIRECTIONS,CONNECTION_TYPES,connectionSet} from './connections.js';
import {generateConnectedMap} from './block-generator.js';
import {isBlock,blockCanvas,extractBlock,validateBlock,openBlock,placeBlock} from './blocks.js';
import {listDesigns,getDesign,saveDesign} from './design-store.js';
import {unitArt} from './red-hats-art.js';
import {PROP_ART} from './prop-art.js';
import {PROPS,EDGES,GROUNDS,propCells} from './environment.js';
import {environmentRenderer} from './environment-renderer.js';
import {bounds,inView,focusSector,invalidateOverview} from './view.js';
import {W,H,MAX_MAP_BYTES,levelOf,roofTop,terrainAt,edgePoints,edgeCells,nearestEdge,blankMap,factoryMap,generateMap,validateMap,parseMap} from './maps.js';
import {brushShape,brushPoints,createEditor,beginStroke,endStroke,applyBrush,replaceMap,undo,redo} from './editor-model.js';
const $=id=>document.getElementById(id),canvas=$('editor-map'),mainCtx=canvas.getContext('2d');
let ctx=mainCtx,renderLevel=0;const compositeLayers=layerCompositor();
let featurePlan=emptyFeaturePlan();let editor=createEditor(factoryMap()),designMode='map';const workspaces={map:editor,block:createEditor(blockCanvas())},designIds={map:null,block:null};const camera={x:0,y:0,zoom:.7},images=new Map();
let viewLevel=0,width=0,height=0,tool='wall',hover=null,pan=null,painting=false,lastPaint='',lastPoint=null,gesture=null,dirty=true;
const art=environmentRenderer(()=>dirty=true,id=>notice('Could not load '+id+' artwork.'));
const toolsHelp={roof:'On the lower level, click the foothold beside an existing upper roof. The nearest edge selects the climb direction. Costs 6 AP up or down, one level only. Upper edge and foothold headroom must be open.','erase-roof':'Remove roof climbs from either endpoint.',texture:'Drag a rectangle to fill the selected floor or roof texture. Release to apply; Escape cancels.',prop:'Place the selected prop. Its highlighted footprint is used for movement and cover.','erase-prop':'Remove a prop or legacy crate, keeping the floor beneath it.','erase-tile':'Remove the floor and any prop on this tile on the selected level. Ground resets to yard. Starts and stairs stay protected.','roof-tile':'Place a 2 × 2 roof module on the selected upper level. Missing floor support is added automatically.',water:'Paint animated water with matching shoreline banks. Water blocks walking. Use bridge decks for crossings.',bridge:'Paint a walkable bridge deck.',ladder:'Connect to the level above with a ladder. Costs 3 AP each way.',stairs:'Connect this tile to the level above. Creates both floor endpoints. Each ascent or descent costs 2 AP.','erase-stairs':'Remove stair connections touching this level.','void':'Remove a floor tile. Unit starts, travel markers and stairs are protected.',yard:'Paint open yard tiles.',floor:'Drag a rectangle to fill concrete flooring. Release to apply; Escape cancels.',crate:'Crates occupy a tile and provide cover. Unit starts and travel markers are protected.',wall:'Drag from a tile boundary to draw a straight wall line. The starting edge locks its direction. Release to apply; Escape cancels.',door:'Place an open doorway along a tile edge. Units and shots can pass through it.','erase-edge':'Remove the selected wall or doorway edge.',room:'Stamp flooring and perimeter walls with two doorways. Click the top-left grid tile.',squad:'Move the selected squad start. Four starts are always retained.',guard:'Place a guard, or change the species and weapon of a guard already on this tile.','remove-guard':'Remove a guard start from this tile.',exit:'Move the travel marker. In play, gather the squad within two tiles to travel.'};
function notice(message){$('notice').textContent=message;}
function project(x,y,z=0){return {x:camera.x+(x-y)*28*camera.zoom,y:camera.y+(x+y)*14*camera.zoom-(z+renderLevel*72)*camera.zoom};}
function unproject(px,py){const a=(px-camera.x)/(28*camera.zoom),b=(py-camera.y+viewLevel*72*camera.zoom)/(14*camera.zoom);return {fx:(a+b)/2,fy:(b-a)/2};}
function hit(e){const r=canvas.getBoundingClientRect(),p=unproject(e.clientX-r.left,e.clientY-r.top);return {...p,x:Math.round(p.fx),y:Math.round(p.fy),edge:nearestEdge(p.fx,p.fy,viewLevel)};}
function fit(){sector();}
function resize(){const r=canvas.getBoundingClientRect(),oldWidth=width,oldHeight=height;const dpr=Math.min(devicePixelRatio||1,2);width=r.width;height=r.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(!oldWidth)sector();else{camera.x+=(width-oldWidth)/2;camera.y+=(height-oldHeight)/2;}dirty=true;}
new ResizeObserver(resize).observe(canvas);
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function diamond(x,y,fill,stroke){const p=project(x,y),a=28*camera.zoom,b=14*camera.zoom;poly([{x:p.x,y:p.y-b},{x:p.x+a,y:p.y},{x:p.x,y:p.y+b},{x:p.x-a,y:p.y}],fill,stroke);}
function label(text,x,y,color='#f0ddb2',offset=0){const p=project(x,y);ctx.font=`${Math.max(10,12*camera.zoom)}px monospace`;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,p.x,p.y+offset);}
function edge(k,kind,highlight=false){if(!highlight&&art.edge(ctx,project,camera.zoom,k,kind))return;const ends=edgePoints(k),a=project(ends[0].x,ends[0].y),b=project(ends[1].x,ends[1].y),h=kind==='wall'?25*camera.zoom:0;
 if(h)poly([a,b,{x:b.x,y:b.y-h},{x:a.x,y:a.y-h}],highlight?'#c3a461':k.startsWith('e')?'#87785b':'#a59470','#4e493a');ctx.strokeStyle=highlight?'#ffdc88':kind==='wall'?'#c7b589':'#79d5db';ctx.lineWidth=(highlight?4:2.5)*camera.zoom;ctx.setLineDash(kind==='door'?[4,3]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y-h);ctx.lineTo(b.x,b.y-h);ctx.stroke();ctx.setLineDash([]);
}
function image(unit){const src=unitArt(unit).src;if(!images.has(src)){const img=new Image();img.onload=()=>dirty=true;img.onerror=()=>notice('A sprite did not load; markers remain usable.');img.src=src;images.set(src,img);}return images.get(src);}
function draw(){mainCtx.fillStyle='#1b2924';mainCtx.fillRect(0,0,width,height);compositeLayers(mainCtx,viewLevel,width,height,(ink,level)=>{ctx=ink;renderLevel=level;try{drawLayer();}finally{ctx=mainCtx;renderLevel=viewLevel;}});ctx=mainCtx;renderLevel=viewLevel;if(camera.zoom>=.2)drawHighlights();}
function drawLayer(){
 const m=editor.map,boundsNow=bounds(camera,width,height);if(designMode==='block'){boundsNow.x0=Math.max(0,boundsNow.x0);boundsNow.y0=Math.max(0,boundsNow.y0);boundsNow.x1=Math.min(23,boundsNow.x1);boundsNow.y1=Math.min(23,boundsNow.y1);}

 for(let y=boundsNow.y0;y<=boundsNow.y1;y++)for(let x=boundsNow.x0;x<=boundsNow.x1;x++){const t=terrainAt(m,x,y,renderLevel);if(t==='void')continue;diamond(x,y,t==='water'?'#365f72':t==='floor'?'#817b5d':(x+y)%2?'#626e4d':'#667250',x%24===0||y%24===0?'#c5bb7977':'#42523988');art.ground(ctx,project,camera.zoom,x,y,t,(a,b)=>terrainAt(m,a,b,renderLevel));diamond(x,y,null,x%24===0||y%24===0?'#c5bb7977':'#42523944');if(t==='bridge')label('═',x,y,'#ccb88c',3);}
 for(const p of m.stairs)if(p.z===renderLevel||p.z+1===renderLevel){diamond(p.x,p.y,'#66bccb77','#a6f3ed');label((p.kind==='ladder'?'L ':'')+(p.z===renderLevel?'↑':'↓'),p.x,p.y,'#effffe',3);}
 for(const link of m.climbs||[])for(const p of [link,roofTop(link)])if(p.z===renderLevel){diamond(p.x,p.y,'#dcb86777','#ffe4a2');label(p.z===link.z?'R ↑':'R ↓',p.x,p.y,'#ffe4a2',3);}
 for(const p of (designMode==='block'?[]:m.exits).filter(p=>levelOf(p)===renderLevel)){diamond(p.x,p.y,'#5dabbc88','#caf4f4');label('TRAVEL',p.x,p.y,'#e0fafa',3);}
 const objects=[];for(const [k,kind]of Object.entries(m.edges)){const cells=edgeCells(k);if(levelOf(cells[0])!==renderLevel||!cells.some(p=>inView(p,boundsNow)))continue;objects.push({depth:(cells[0].x+cells[0].y+cells[1].x+cells[1].y)/2,type:'edge',k,kind});}
 for(let y=boundsNow.y0;y<=boundsNow.y1;y++)for(let x=boundsNow.x0;x<=boundsNow.x1;x++)if(terrainAt(m,x,y,renderLevel)==='crate')objects.push({depth:x+y,type:'crate',x,y});
 for(const p of m.props||[])if(levelOf(p)===renderLevel&&propCells(p).some(q=>inView(q,boundsNow)))objects.push({...p,depth:Math.max(...propCells(p).map(q=>q.x+q.y)),type:'prop'});
 (designMode==='block'?[]:m.starts).forEach((p,i)=>objects.push({...p,depth:p.x+p.y,type:'unit',species:['horse','goat','donkey','sheep'][i],label:String(i+1),color:'#f3d780'}));m.guards.forEach((p,i)=>objects.push({...p,depth:p.x+p.y,type:'unit',label:`G${i+1}`,color:'#ff9c7b'}));
 objects.sort((a,b)=>(PROPS[a.kind]?.groundLayer?0:1)-(PROPS[b.kind]?.groundLayer?0:1)||a.depth-b.depth||(a.type==='unit'?1:-1));for(const o of objects){if(o.type==='unit'&&(levelOf(o)!==renderLevel||!inView(o,boundsNow)))continue;if(o.type==='prop'){art.prop(ctx,project,camera.zoom,o);continue;}if(o.type==='edge'){edge(o.k,o.kind);continue;}const p=project(o.x,o.y);if(o.type==='crate'){if(art.prop(ctx,project,camera.zoom,{...o,kind:'crate-wood'}))continue;diamond(o.x,o.y,'#ab824b','#dab273');poly([{x:p.x-22*camera.zoom,y:p.y},{x:p.x,y:p.y+11*camera.zoom},{x:p.x,y:p.y-3*camera.zoom},{x:p.x-22*camera.zoom,y:p.y-14*camera.zoom}],'#7b603c');poly([{x:p.x,y:p.y+11*camera.zoom},{x:p.x+22*camera.zoom,y:p.y},{x:p.x+22*camera.zoom,y:p.y-14*camera.zoom},{x:p.x,y:p.y-3*camera.zoom}],'#967343');poly([{x:p.x,y:p.y-25*camera.zoom},{x:p.x+22*camera.zoom,y:p.y-14*camera.zoom},{x:p.x,y:p.y-3*camera.zoom},{x:p.x-22*camera.zoom,y:p.y-14*camera.zoom}],'#bc965a','#d3b47c');continue;}
 diamond(o.x,o.y,null,o.color);const img=image(o),frame=unitArt(o),spriteWidth=frame.width/4*camera.zoom;if(img.complete&&img.naturalWidth)ctx.drawImage(img,p.x-spriteWidth/2,p.y-59*camera.zoom,spriteWidth,64*camera.zoom);ctx.save();ctx.translate(p.x,p.y+5*camera.zoom);drawFlamethrower(ctx,o,camera.zoom);ctx.restore();label(o.label,o.x,o.y,o.color,18*camera.zoom);
 }
}
function drawHighlights(){const boundsNow=bounds(camera,width,height);
 if(renderLevel===viewLevel&&gesture){for(const p of brushPoints(tool,gesture.start,gesture.end,designMode==='block'?24:W)){if(p.edge)edge(p.edge,'wall',true);else if(inView(p,boundsNow))diamond(p.x,p.y,'#e6c67a55','#ffe4a7');}}
 if(renderLevel===viewLevel&&!gesture&&hover&&hover.x>=0&&hover.y>=0&&hover.x<W&&hover.y<H){if(['wall','door','erase-edge','roof'].includes(tool))edge(hover.edge,tool==='door'?'door':'wall',true);else if(['prop','roof-tile'].includes(tool)){for(const p of propCells({x:hover.x,y:hover.y,z:renderLevel,kind:options().propKind,rotated:$('rotate').checked}))diamond(p.x,p.y,'#dec98655','#ffe0a088');}else if(tool==='room'){const opt=options(),w=opt.rotated?opt.height:opt.width,h=opt.rotated?opt.width:opt.height;for(let dy=0;dy<h;dy++)for(let dx=0;dx<w;dx++){const x=hover.x+dx,y=hover.y+dy;if(x<W&&y<H)diamond(x,y,'#dec98655','#ffe0a088');}}else diamond(hover.x,hover.y,'#e6c67a55','#ffe4a7');}
}
let validationId=0,validationErrors=[],validationPending=false;
const validator=new Worker(new URL('./map-validation-worker.js',import.meta.url),{type:'module'});
function renderValidation(errors,pending=false){$('validation').replaceChildren();for(const message of pending?['Checking paths across all three levels…']:errors.length?errors.slice(0,6):[designMode==='block'?'Block ready to save. Place it into a full map to playtest.':'Ready to play. All starts and the travel marker are reachable.']){const li=document.createElement('li');li.textContent=message;$('validation').append(li);}$('validation').classList.toggle('invalid',errors.length>0);$('test').disabled=designMode==='block'||pending||errors.length>0;}
validator.onmessage=({data})=>{if(data.id!==validationId)return;validationPending=false;validationErrors=data.errors;renderValidation(data.errors);};
validator.onerror=()=>{validationPending=false;validationErrors=['Map validation could not run. Reload the editor before playtesting.'];renderValidation(validationErrors);};
function update(){featurePlan=structuredClone(editor.map.generationPlan||editor.map.featurePlan||emptyFeaturePlan());renderFeaturePlan();updateConnections();invalidateOverview(editor.map);let errors;try{errors=designMode==='block'?(validateBlock(extractBlock(editor.map)),[]):validateMap(editor.map,{connectivity:false});}catch(e){errors=[e.message];}validationErrors=errors;validationPending=designMode==='map'&&!errors.length;validationId++;renderValidation(errors,validationPending);if(validationPending)validator.postMessage({id:validationId,map:editor.map});$('export').disabled=errors.length>0;$('undo').disabled=!editor.undo.length;$('redo').disabled=!editor.redo.length;$('map-count').textContent=(designMode==='block'?'BLOCK CHECK ·24×24 / ':'MAP CHECK · 4 SQUAD / ')+editor.map.guards.length+' GUARDS / 3 LEVELS';$('map-name').value=editor.map.name;if(editor.map.sectors)$('map-count').textContent+=' / TWO BRIDGES';dirty=true;}
function options(){const [width,height]=$('room-size').value.split(',').map(Number);return {propKind:tool==='roof-tile'?$('roof-kind').value:$('prop-kind').value,edgeKind:$('edge-kind').value,groundKind:$('ground-kind').value,level:viewLevel,width,height,rotated:$('rotate').checked,slot:Number($('slot').value),species:$('species').value,outfit:$('outfit').value,weapon:$('weapon').value};}
function paint(p){if(designMode==='block'){if(p.x<0||p.x>=24||p.y<0||p.y>=24){notice('Block designs are limited to24×24 tiles.');return;}if(['squad','exit'].includes(tool)){notice('Squad starts and travel markers belong to full maps.');return;}if(tool==='room'){const o=options(),w=o.rotated?o.height:o.width,h=o.rotated?o.width:o.height;if(p.x+w>24||p.y+h>24){notice('The room must fit inside the24×24 block.');return;}}if(['prop','roof-tile'].includes(tool)&&propCells({x:p.x,y:p.y,z:viewLevel,kind:options().propKind,rotated:$('rotate').checked}).some(q=>q.x>=24||q.y>=24)){notice('The prop must fit inside the block.');return;}}if(camera.zoom<.2){notice("Double-click a sector to zoom in before editing.");return;}const id=['wall','door','erase-edge'].includes(tool)?p.edge:`${p.x},${p.y}`;if(id===lastPaint)return;lastPaint=id;const result=applyBrush(editor,tool,p.x,p.y,p.edge,options());if(result)notice(result);else notice(`${tool.replaceAll('-',' ')} placed. Undo restores the previous stroke.`);dirty=true;}
function finish(commit=false){if(gesture){if(commit===true){let skipped=0;for(const p of brushPoints(tool,gesture.start,gesture.end,designMode==='block'?24:W)){if(applyBrush(editor,tool,p.x,p.y,p.edge,gesture.options))skipped++;}notice(skipped?'Selection applied; '+skipped+' protected or invalid tiles skipped.':'Selection applied. Undo restores the entire selection.');}gesture=null;dirty=true;}if(painting){endStroke(editor);painting=false;lastPoint=null;lastPaint='';update();}pan=null;}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);hover=hit(e);if(e.button===2||e.button===1||e.altKey){pan={x:e.clientX,y:e.clientY};return;}if(e.button!==0)return;if(camera.zoom<.2){notice('Double-click a sector to zoom in before editing.');return;}beginStroke(editor);painting=true;if(brushShape(tool)){gesture={start:hover,end:hover,options:options()};dirty=true;return;}paint(hover);lastPoint=hover;if(['prop','roof-tile','erase-prop','stairs','ladder','roof','erase-roof','room','squad','guard','remove-guard','exit'].includes(tool))finish();});
canvas.addEventListener('pointermove',e=>{if(pan){camera.x+=e.clientX-pan.x;camera.y+=e.clientY-pan.y;pan={x:e.clientX,y:e.clientY};dirty=true;return;}hover=hit(e);$('cursor-info').textContent=`${hover.x}, ${hover.y} · ${['wall','door','erase-edge'].includes(tool)?'Edge '+hover.edge:tool.replaceAll('-',' ')} · Level ${viewLevel+1} · Sector ${Math.floor(hover.x/24)+1},${Math.floor(hover.y/24)+1} · ${designMode==='block'?24:W} × ${designMode==='block'?24:H} tiles`;if(gesture){gesture.end=hover;dirty=true;return;}if(painting){if(lastPoint){const n=Math.ceil(Math.max(Math.abs(hover.fx-lastPoint.fx),Math.abs(hover.fy-lastPoint.fy))*5);for(let i=1;i<=n;i++){const fx=lastPoint.fx+(hover.fx-lastPoint.fx)*i/n,fy=lastPoint.fy+(hover.fy-lastPoint.fy)*i/n;paint({fx,fy,x:Math.round(fx),y:Math.round(fy),edge:nearestEdge(fx,fy,viewLevel)});}}else paint(hover);lastPoint=hover;}dirty=true;});
canvas.addEventListener('pointerup',e=>{if(gesture)gesture.end=hit(e);finish(true);});canvas.addEventListener('pointercancel',finish);canvas.addEventListener('lostpointercapture',finish);canvas.addEventListener('pointerleave',()=>{hover=null;dirty=true;});
function zoom(factor,px=width/2,py=height/2){const old=camera.zoom;camera.zoom=Math.max(.2,Math.min(2.4,old*factor));camera.x=px+(camera.x-px)*camera.zoom/old;camera.y=py+(camera.y-py)*camera.zoom/old;dirty=true;}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(e.deltaY<0?1.12:1/1.12,e.clientX-r.left,e.clientY-r.top);hover=hit(e);},{passive:false});
$('tools').onclick=e=>{const b=e.target.closest('[data-tool]');if(!b)return;finish();tool=b.dataset.tool;for(const button of $('tools').querySelectorAll('button'))button.setAttribute('aria-pressed',button===b);$('tool-help').textContent=toolsHelp[tool];assetRules();dirty=true;};
$('undo').onclick=()=>{finish();undo(editor);update();};$('redo').onclick=()=>{finish();redo(editor);update();};$('fit').onclick=fit;$('in').onclick=()=>zoom(1.2);$('out').onclick=()=>zoom(1/1.2);
$('map-name').oninput=()=>{beginStroke(editor);editor.map.name=$('map-name').value.trim()||'Untitled design';};
$('map-name').onchange=()=>{beginStroke(editor);editor.map.name=$('map-name').value.trim()||'Untitled local map';endStroke(editor);update();};
for(const id of ['room-size','rotate'])$(id).onchange=()=>dirty=true;
$('generate').onclick=()=>{if(designMode==='block')return;designIds.map=null;const seed=Number($('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){notice('Use a whole-number seed between 0 and 4294967295.');return;}const layout=$('layout').value;replaceMap(editor,generateMap(seed,`Generated ${seed}`,46,{layout:layout==='factory'?'factory':'river',orientation:layout.endsWith('ew')?'ew':'ns'}));update();notice(`Generated seed ${seed}. Undo returns to your previous map.`);};
$('blank').onclick=()=>{designIds[designMode]=null;replaceMap(editor,designMode==='block'?blockCanvas():blankMap());update();notice('Blank map ready. Four starts and one travel marker are included. Undo restores the old map.');};$('factory').onclick=()=>{if(designMode==='block')return;designIds.map=null;replaceMap(editor,factoryMap());update();notice('Factory template loaded. Undo restores the previous map.');};
$('save').onclick=()=>{try{localStorage.setItem(designMode==='block'?'red-shift-block-draft-v1':'red-shift-map-draft-v1',JSON.stringify(currentDesign()));notice('Draft saved in this browser. Export JSON for a portable backup.');}catch{notice('Browser storage is unavailable or full. Export JSON instead.');}};
$('load').onclick=()=>{try{const text=localStorage.getItem(designMode==='block'?'red-shift-block-draft-v1':'red-shift-map-draft-v1');if(!text){notice('No saved draft in this browser yet.');return;}const raw=JSON.parse(text);openDesign(isBlock(raw)?validateBlock(raw):parseMap(text,{allowDisconnected:true}));notice('Draft loaded. Undo restores your previous map.');}catch(e){notice('Could not load draft: '+e.message);}};
$('export').onclick=()=>{let design;try{design=currentDesign();}catch(e){notice(e.message);return;}const blob=new Blob([JSON.stringify(design)],{type:'application/json'});if(blob.size>MAX_MAP_BYTES){notice('This map exceeds the 4 MB portable file limit. Remove unused details before export.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(editor.map.name.replace(/[^a-z0-9_-]/gi,'-')||'local-map')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice(validationPending||validationErrors.length?'Draft exported. Check reachability before playtesting.':'Map exported as JSON.');};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>MAX_MAP_BYTES)throw Error('Map file exceeds 4 MB.');const text=await file.text(),raw=JSON.parse(text);openDesign(isBlock(raw)?validateBlock(raw):parseMap(text,{allowDisconnected:true}));notice('Map imported. Fix any reachability errors before playtesting.');}catch(e){notice('Import rejected: '+e.message);}finally{$('file').value='';}};
$('test').onclick=()=>{if(validationPending){notice('Wait for the map check to finish.');return;}const errors=validationErrors;if(errors.length){notice(errors[0]);return;}try{sessionStorage.setItem('red-shift-playtest',JSON.stringify(editor.map));$('test-frame').src='index.html?map=custom&test='+Date.now();$('playtest').showModal();}catch{notice('Session storage is unavailable. Allow local browser storage to playtest.');}};
function closeTest(){$('playtest').close();$('test-frame').src='about:blank';}$('close-test').onclick=closeTest;$('playtest').addEventListener('cancel',()=>{$('test-frame').src='about:blank';});
const panKeys=new Set(),panDirections={w:[0,1],arrowup:[0,1],s:[0,-1],arrowdown:[0,-1],a:[1,0],arrowleft:[1,0],d:[-1,0],arrowright:[-1,0]};
const keyboardBlocked=()=>document.querySelector('dialog[open]')||document.activeElement?.matches('input,select,textarea,[contenteditable]:not([contenteditable="false"])');
document.addEventListener('keydown',e=>{if(keyboardBlocked())return;const k=e.key.toLowerCase();if(e.key==='Escape'){panKeys.clear();finish();notice('Selection cancelled.');return;}if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();finish();e.shiftKey?redo(editor):undo(editor);update();return;}if(e.ctrlKey||e.metaKey||e.altKey)return;if(panDirections[k]){e.preventDefault();if(painting||pan)return;panKeys.add(k);}});
document.addEventListener('keyup',e=>panKeys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>panKeys.clear());
document.addEventListener('visibilitychange',()=>panKeys.clear());
document.addEventListener('focusin',()=>{if(keyboardBlocked())panKeys.clear();});
$('weapon').replaceChildren(...Object.entries(WEAPONS).map(([id,w])=>new Option(`${w.name} · ${w.range} tiles`,id)));$('weapon').value='pistol';
for(const [id,values]of [['roof-kind',Object.keys(PROPS).filter(k=>k.startsWith('roof-'))],['prop-kind',Object.keys(PROPS)],['edge-kind',Object.keys(EDGES).filter(k=>!['wall','door'].includes(k))],['ground-kind',GROUNDS]]){const groups=new Map();for(const v of values){const category=PROP_ART[v]?.file.split('/')[0],label=({facility:'Lab and medical',hospital:'Hospital',foliage:'Foliage',containers:'Containers',loot:'Field supplies (decoration)'})[category]||(v.startsWith('roof-')?'Roof modules':'Factory');if(!groups.has(label)){const group=document.createElement('optgroup');group.label=label;$(id).append(group);groups.set(label,group);}const o=document.createElement('option');o.value=v;o.textContent=v.replaceAll('-',' ');groups.get(label).append(o);}}
function assetRules(){if(tool==='wall'){const e=EDGES[$('edge-kind').value];$('asset-rules').textContent=$('edge-kind').value.replaceAll('-',' ')+' · '+(e.solid?'blocks crossing':'open passage')+' · '+(e.window?'sight through window aperture':e.opaque?'blocks sight':'allows sight')+' · '+(e.cover?'cover −'+e.cover+'%':'no cover');dirty=true;return;}const p=PROPS[options().propKind],w=$('rotate').checked?p.h:p.w,h=$('rotate').checked?p.w:p.h;$('asset-rules').textContent=w+' × '+h+' tiles · '+(p.solid?'blocks movement':'walkable')+' · '+(p.tall?'blocks sight':p.cover?'low cover':'no cover')+' · Selected edge: '+$('edge-kind').value.replaceAll('-',' ');dirty=true;}
for(const id of ['roof-kind','prop-kind','edge-kind','ground-kind','rotate'])$(id).addEventListener('change',assetRules);assetRules();
function sector(){const sx=designMode==='block'?0:Number($('sector-x').value)-1,sy=designMode==='block'?0:Number($('sector-y').value)-1;if(!Number.isInteger(sx)||!Number.isInteger(sy)||sx<0||sy<0||sx>9||sy>9){notice('Choose sector coordinates from 1 to 10.');return;}focusSector(camera,width,height,sx,sy);hover=null;$('cursor-info').textContent='Sector '+(sx+1)+', '+(sy+1)+' · Level '+(viewLevel+1)+' · 24 × 24 tiles';dirty=true;}
$('sector').onclick=sector;$('level').onchange=()=>{finish();viewLevel=Number($('level').value);hover=null;dirty=true;};
canvas.addEventListener('dblclick',e=>{if(designMode==='block'||camera.zoom>=.2)return;const p=hit(e);if(p.x<0||p.y<0||p.x>=W||p.y>=H)return;$('sector-x').value=Math.floor(p.x/24)+1;$('sector-y').value=Math.floor(p.y/24)+1;sector();});
let lastWaterFrame=0,lastPanFrame=0;function frame(now){const elapsed=Math.min(50,now-(lastPanFrame||now));lastPanFrame=now;if(keyboardBlocked()||document.hidden||painting||pan)panKeys.clear();if(panKeys.size){let x=0,y=0;for(const k of panKeys){x+=panDirections[k][0];y+=panDirections[k][1];}const length=Math.hypot(x,y);if(length){camera.x+=x/length*elapsed*.5;camera.y+=y/length*elapsed*.5;hover=null;dirty=true;}}if(dirty||!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&now-lastWaterFrame>=125){draw();dirty=false;lastWaterFrame=now;}requestAnimationFrame(frame);}resize();update();requestAnimationFrame(frame);

function currentDesign(){if(designMode==='block')return validateBlock(extractBlock(editor.map));const errors=validateMap(editor.map,{connectivity:false});if(errors.length)throw Error(errors[0]);return structuredClone(editor.map);}
function switchWorkspace(mode){finish();designMode=mode;editor=workspaces[mode];$('design-size').value=mode;for(const id of ['sector-x','sector-y','generate','factory','capture-block','place-block'])$(id).disabled=mode==='block';$('scope-help').textContent=mode==='block'?'24×24 block / three levels. Save and place it into a full map to playtest.':'240×240 map /100 sectors / three levels. Both workspaces retain their current designs.';$('blank').textContent=mode==='block'?'New blank block':'New blank map';$('sector-x').value=1;$('sector-y').value=1;viewLevel=0;$('level').value='0';sector();update();}
function openDesign(d,id=null){switchWorkspace(isBlock(d)?'block':'map');replaceMap(editor,isBlock(d)?openBlock(d):d);designIds[designMode]=id;update();}
async function refreshLibrary(selected=''){const rows=await listDesigns();$('design-library').replaceChildren(new Option('Choose a saved design',''));for(const r of rows.sort((a,b)=>b.updated-a.updated))$('design-library').append(new Option((isBlock(r.design)?'24×24 · ':'240×240 · ')+r.design.name+' · '+new Date(r.updated).toLocaleString(),r.id));$('design-library').value=selected;}
async function persist(copy=false){try{const mode=designMode,source=editor.map,design=currentDesign(),id=copy?crypto.randomUUID():(designIds[mode]||crypto.randomUUID());await saveDesign({id,design,updated:Date.now()});if(workspaces[mode].map===source)designIds[mode]=id;await refreshLibrary(designMode===mode?id:'');notice('Design saved. Export JSON for a portable backup.');}catch(e){notice('Save failed: '+e.message+'. Export JSON for a backup.');}}
$('design-size').onchange=()=>switchWorkspace($('design-size').value);
$('save-design').onclick=()=>persist();$('save-copy').onclick=()=>persist(true);
$('open-design').onclick=async()=>{try{const r=await getDesign($('design-library').value);if(!r)throw Error('Choose a saved design.');const d=isBlock(r.design)?validateBlock(r.design):parseMap(JSON.stringify(r.design),{allowDisconnected:true});openDesign(d,r.id);notice('Saved design opened. Undo restores the previous design in this workspace.');}catch(e){notice(e.message);}};
$('capture-block').onclick=async()=>{try{const d=validateBlock(extractBlock(editor.map,Number($('sector-x').value)-1,Number($('sector-y').value)-1));d.name=editor.map.name+' sector '+$('sector-x').value+','+$('sector-y').value;d.name=d.name.slice(0,60);const id=crypto.randomUUID();await saveDesign({id,design:d,updated:Date.now()});await refreshLibrary(id);notice('Sector saved as a reusable24×24 block.');}catch(e){notice(e.message);}};
$('place-block').onclick=async()=>{try{const destination=editor,source=editor.map,sx=Number($('sector-x').value)-1,sy=Number($('sector-y').value)-1;if(designMode!=='map')throw Error('Switch to the full map workspace.');const r=await getDesign($('design-library').value);if(editor!==destination||editor.map!==source||designMode!=='map')throw Error('Workspace changed; select the block again.');if(!r||!isBlock(r.design))throw Error('Select a24×24 block from the library.');const next=placeBlock(editor.map,r.design,sx,sy);replaceMap(editor,next);update();notice('Block placed across all three levels. Undo restores the sector.');}catch(e){notice('Placement rejected: '+e.message);}};
refreshLibrary().catch(()=>notice('Browser library unavailable. Import/export JSON still works.'));

function updateConnections(){const types=editor.map.blockConnections?.['0,0'];for(const d of DIRECTIONS){$('connection-'+d).disabled=designMode!=='block';$('connection-'+d).value=designMode==='block'?(types?.[d]||'none'):'none';}$('apply-connections').disabled=designMode!=='block';$('generate-connected').disabled=designMode!=='map';$('connection-help').textContent=designMode==='block'?(types?'Connections assigned. Rechecked after edits and when placed beside another connected block.':'No rules assigned yet. Older blocks remain manually placeable.'):'Open a reusable block to assign its connections.';}
$('apply-connections').onclick=()=>{finish();try{const types=Object.fromEntries(DIRECTIONS.map(d=>[d,$('connection-'+d).value]));connectionSet(editor.map,0,0,types);beginStroke(editor);editor.map.blockConnections={'0,0':types};endStroke(editor);update();notice('Connections assigned. Save the block to include it in procedural generation.');}catch(e){notice(e.message);}};
$('generate-connected').onclick=async()=>{finish();const destination=editor,source=editor.map;try{const rows=await listDesigns();if(editor!==destination||editor.map!==source||designMode!=='map')throw Error('Workspace changed; generate again from the full map.');const next=generateConnectedMap(rows.map(r=>r.design).filter(d=>isBlock(d)&&d.connections),Number($('seed').value),featurePlan);replaceMap(editor,next);designIds.map=null;update();notice('Generated 100 matching blocks. Undo restores your previous map.');}catch(e){notice('Generation failed: '+e.message);}};

function renderFeaturePlan(){const host=$('feature-lines');if(!host.children.length){for(let i=0;i<10;i++){const row=document.createElement('div');row.className='feature-pair';for(const axis of ['rows','columns']){const label=document.createElement('label');label.textContent=(axis==='rows'?'Row ':'Column ')+(i+1);const select=document.createElement('select');select.id='feature-'+axis+'-'+i;for(const type of CONNECTION_TYPES)select.add(new Option(type,type));select.onchange=()=>{featurePlan[axis][i]=select.value;saveFeaturePlan();};label.append(select);row.append(label);}host.append(row);}}for(let i=0;i<10;i++)for(const axis of ['rows','columns']){$('feature-'+axis+'-'+i).value=featurePlan[axis][i];$('feature-'+axis+'-'+i).disabled=designMode!=='map';}$('seed-lines').disabled=designMode!=='map';const preview=$('feature-preview');preview.replaceChildren();for(let y=0;y<10;y++)for(let x=0;x<10;x++){const c=requiredConnections(featurePlan,x,y),cell=document.createElement('span');const colors={none:'transparent',road:'#d5bd83',river:'#70bdd8',fence:'#8dc47e',wall:'#cc8e79',cliff:'#bb9bdd'};cell.style.backgroundImage='linear-gradient(to bottom, transparent 38%, '+colors[c.east]+' 38%, '+colors[c.east]+' 62%, transparent 62%),linear-gradient(to right, transparent 38%, '+colors[c.north]+' 38%, '+colors[c.north]+' 62%, transparent 62%)';cell.title='Sector '+(x+1)+','+(y+1)+': '+Object.entries(c).map(([k,v])=>k+' '+v).join(', ');preview.append(cell);}}
$('seed-lines').onclick=()=>{try{featurePlan=seededFeaturePlan(Number($('seed').value));saveFeaturePlan();}catch(e){notice(e.message);return;}notice('Planned one full road row and one full fence column. Generation uses matching saved blocks.');};

function saveFeaturePlan(){finish();beginStroke(editor);editor.map.generationPlan=structuredClone(featurePlan);endStroke(editor);update();}
