import {CONNECTION_TYPES,DIRECTIONS,connectionSet,connectionsMatch} from './connections.js';
export const emptyFeaturePlan=()=>({version:1,rows:Array(10).fill('none'),columns:Array(10).fill('none')});
export function validateFeaturePlan(plan){if(!plan||plan.version!==1||['rows','columns'].some(k=>!Array.isArray(plan[k])||plan[k].length!==10||plan[k].some(t=>!CONNECTION_TYPES.includes(t))))throw Error('Feature plan needs ten rows and ten columns, each with one element.');return plan;}
export function requiredConnections(plan,x,y){validateFeaturePlan(plan);return {north:plan.columns[x],east:plan.rows[y],south:plan.columns[x],west:plan.rows[y]};}
export function plannedBlock(types,plan,x,y){const required=requiredConnections(plan,x,y);return DIRECTIONS.every(d=>types[d]===required[d]);}
export function seededFeaturePlan(seed){if(!Number.isInteger(seed)||seed<0||seed>4294967295)throw Error('Use a whole-number seed between 0 and 4294967295.');const p=emptyFeaturePlan();let n=seed>>>0;const next=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n%10;};p.rows[next()]='road';p.columns[next()]='fence';return p;}
export function validatePlannedMap(m){if(m.generationPlan!==undefined){try{validateFeaturePlan(m.generationPlan);}catch(e){return [e.message];}}if(m.featurePlan===undefined)return [];try{validateFeaturePlan(m.featurePlan);}catch(e){return [e.message];}const errors=[];for(let y=0;y<10;y++)for(let x=0;x<10;x++){const types=m.blockConnections?.[x+','+y];if(!types||!plannedBlock(types,m.featurePlan,x,y))errors.push('Feature plan mismatch at sector '+(x+1)+','+(y+1)+'.');try{const ports=connectionSet(m,x,y,types);if(m.featurePlan.rows[y]!=='none'&&!connectionsMatch(ports.east,ports.west)||m.featurePlan.columns[x]!=='none'&&!connectionsMatch(ports.north,ports.south))errors.push('Feature line changes alignment inside sector '+(x+1)+','+(y+1)+'.');}catch(e){errors.push(e.message);}const ew=m.featurePlan.rows[y]==='road',ns=m.featurePlan.columns[x]==='road';if(ew||ns){for(let dy=0;dy<24;dy++)for(let dx=0;dx<24;dx++){const corridor=ew&&dy>=9&&dy<=14||ns&&dx>=9&&dx<=14,t=m.terrain[y*24+dy][x*24+dx];if(corridor&&!['ground-asphalt','bridge'].includes(t)||!corridor&&t==='ground-asphalt'){errors.push('Road alignment broken at sector '+(x+1)+','+(y+1)+': keep roads centered and six tiles wide.');dy=24;break;}}}}return errors;}

export function fitsFeaturePlan(d,ports,plan,x,y){return plannedBlock(d.connections,plan,x,y)&&(plan.rows[y]==='none'||connectionsMatch(ports.east,ports.west))&&(plan.columns[x]==='none'||connectionsMatch(ports.north,ports.south));}
