import {sightOf} from './perception.js';
export const SPECIES_TRAITS={horse:{hp:10,ap:0,accuracy:0,stealth:0,label:'Sturdy: +10 HP; 350° field, 60° binocular'},goat:{hp:-10,ap:1,accuracy:0,stealth:5,label:'Agile: −10 HP, +1 AP, +5 stealth; 330° field, 50° binocular'},donkey:{hp:20,ap:-1,accuracy:-5,stealth:0,label:'Tough: +20 HP, −1 AP, −5 accuracy; 350° field, 60° binocular'},sheep:{hp:0,ap:0,accuracy:-10,stealth:0,label:'Wide awareness: −10 accuracy; 300° field, 35° binocular'}};
export const SKILLS={shooting:{label:'Shooting',effect:'+2 accuracy'},medical:{label:'Medical',effect:'+5 medical (maximum100)'},stealth:{label:'Stealth',effect:'+5 stealth (maximum100)'},vitality:{label:'Vitality',effect:'+5 maximum HP'},mobility:{label:'Mobility',effect:'+1 maximum AP per3 points'}};
export const BASE={hp:100,ap:12,accuracy:85,stealth:20}; // the comrades' base; a hired merc carries its own (recruits.js, `u.base`)
export function recalculate(u){const t=SPECIES_TRAITS[u.species]||{hp:0,ap:0,accuracy:0,stealth:0},k=u.skills,b=u.base||BASE;u.maxHp=b.hp+t.hp+k.vitality*5;u.maxAp=b.ap+t.ap+Math.floor(k.mobility/3);u.accuracy=b.accuracy+t.accuracy+k.shooting*2;u.medical=Math.min(100,u.baseMedical+k.medical*5);u.stealth=Math.min(100,b.stealth+t.stealth+k.stealth*5);u.cone=sightOf(u).field;u.hp=Math.min(u.hp,u.maxHp);u.ap=Math.min(u.ap,u.maxAp);}
export function initProgression(u){u.xp=0;u.level=1;u.skillPoints=0;u.baseMedical=u.medical;u.skills=Object.fromEntries(Object.keys(SKILLS).map(k=>[k,0]));recalculate(u);u.hp=u.maxHp;u.ap=u.maxAp;}
export function awardXP(u,amount){u.xp+=amount;const level=Math.min(10,1+Math.floor(u.xp/100));u.skillPoints+=(level-u.level)*3;u.level=level;}
export function awardCombatXP(s){for(const u of s.units)if(u.team==='squad'&&!['dead','captured','quit'].includes(u.casualty))awardXP(u,25);}
export function train(u,skill){if(!Object.hasOwn(SKILLS,skill)||!Number.isInteger(u.skillPoints)||u.skillPoints<1||u.skills[skill]>=20||skill==='medical'&&u.medical>=100||skill==='stealth'&&u.stealth>=100)return false;u.skillPoints--;u.skills[skill]++;recalculate(u);return true;}
