// Generated by tools/catalog-environment.py; alpha >= 64.
export const PROP_ART = {
  "botanical-chamber": {
    "file": "facility/botanical-chamber.png",
    "crop": [
      382,
      44,
      899,
      1220
    ]
  },
  "jail-bars": {
    "file": "facility/jail-bars.png",
    "crop": [
      334,
      9,
      920,
      1205
    ],
    "baseline": [
      350,
      1190,
      907,
      950,
      900
    ],
    "height": 62
  },
  "jail-door-closed": {
    "file": "facility/jail-door-closed.png",
    "crop": [
      335,
      9,
      920,
      1204
    ],
    "baseline": [
      350,
      1190,
      907,
      950,
      900
    ],
    "height": 62
  },
  "lab-bench": {
    "file": "facility/lab-bench.png",
    "crop": [
      58,
      84,
      1224,
      1238
    ]
  },
  "lab-control-console": {
    "file": "facility/lab-control-console.png",
    "crop": [
      214,
      50,
      1085,
      1208
    ]
  },
  "medical-exam-table": {
    "file": "facility/medical-exam-table.png",
    "crop": [
      47,
      66,
      1221,
      1196
    ]
  },
  "medical-surgical-table": {
    "file": "facility/medical-surgical-table.png",
    "crop": [
      34,
      55,
      1218,
      1169
    ]
  },
  "medicine-cabinet": {
    "file": "facility/medicine-cabinet.png",
    "crop": [
      298,
      20,
      992,
      1243
    ]
  },
  "bedside-monitor": {
    "file": "hospital/bedside-monitor.png",
    "crop": [
      265,
      56,
      991,
      1207
    ]
  },
  "hospital-bed": {
    "file": "hospital/hospital-bed.png",
    "crop": [
      26,
      66,
      1235,
      1193
    ]
  },
  "instrument-trolley": {
    "file": "hospital/instrument-trolley.png",
    "crop": [
      204,
      50,
      1122,
      1211
    ]
  },
  "iv-stand": {
    "file": "hospital/iv-stand.png",
    "crop": [
      365,
      32,
      902,
      1221
    ]
  },
  "scrub-sink": {
    "file": "hospital/scrub-sink.png",
    "crop": [
      75,
      121,
      1212,
      1198
    ]
  },
  "wheeled-stretcher": {
    "file": "hospital/wheeled-stretcher.png",
    "crop": [
      42,
      143,
      1222,
      1171
    ]
  },
  "medicine-cabinet-closed": {
    "file": "containers/medicine-cabinet-closed.png",
    "crop": [
      298,
      20,
      992,
      1243
    ]
  },
  "medicine-cabinet-open": {
    "file": "containers/medicine-cabinet-open.png",
    "crop": [
      289,
      18,
      1136,
      1244
    ]
  },
  "supply-chest-closed": {
    "file": "containers/supply-chest-closed.png",
    "crop": [
      63,
      181,
      1207,
      1125
    ]
  },
  "supply-chest-open": {
    "file": "containers/supply-chest-open.png",
    "crop": [
      61,
      59,
      1206,
      1173
    ]
  },
  "toolbox-closed": {
    "file": "containers/toolbox-closed.png",
    "crop": [
      107,
      417,
      1199,
      1204
    ]
  },
  "toolbox-open": {
    "file": "containers/toolbox-open.png",
    "crop": [
      89,
      53,
      1203,
      1204
    ]
  },
  "wooden-crate-closed": {
    "file": "containers/wooden-crate-closed.png",
    "crop": [
      119,
      71,
      1135,
      1193
    ]
  },
  "wooden-crate-open": {
    "file": "containers/wooden-crate-open.png",
    "crop": [
      119,
      63,
      1138,
      1195
    ]
  },
  "ammo-assault": {
    "file": "loot/ammo-assault.png",
    "crop": [
      103,
      130,
      1164,
      1124
    ]
  },
  "ammo-pistol": {
    "file": "loot/ammo-pistol.png",
    "crop": [
      169,
      245,
      1084,
      983
    ]
  },
  "ammo-rifle": {
    "file": "loot/ammo-rifle.png",
    "crop": [
      112,
      181,
      1196,
      1151
    ]
  },
  "first-aid-kit": {
    "file": "loot/first-aid-kit.png",
    "crop": [
      83,
      135,
      1178,
      1134
    ]
  },
  "gun-assault": {
    "file": "loot/gun-assault.png",
    "crop": [
      50,
      221,
      1220,
      1046
    ]
  },
  "gun-pistol": {
    "file": "loot/gun-pistol.png",
    "crop": [
      164,
      163,
      1203,
      1160
    ]
  },
  "gun-rifle": {
    "file": "loot/gun-rifle.png",
    "crop": [
      20,
      130,
      1230,
      1101
    ]
  },
  "spare-parts": {
    "file": "loot/spare-parts.png",
    "crop": [
      102,
      120,
      1214,
      1081
    ]
  },
  "wire-cutters": {
    "file": "loot/wire-cutters.png",
    "crop": [
      95,
      116,
      1190,
      1184
    ]
  },
  "fence-cut": {
    "file": "fence-chainlink-cut.png",
    "crop": [
      119,
      32,
      1142,
      1216
    ],
    "baseline": [
      230,
      1165,
      1110,
      694,
      530
    ],
    "height": 44
  }
};
