import {W,H,SECTOR,levelOf,terrainAt} from './maps.js';
export function bounds(camera,width,height){const pts=[[-80,-100],[width+80,-100],[-80,height+120],[width+80,height+120]].map(([x,y])=>{const a=(x-camera.x)/(28*camera.zoom),b=(y-camera.y)/(14*camera.zoom);return {x:(a+b)/2,y:(b-a)/2};});return {x0:Math.max(0,Math.floor(Math.min(...pts.map(p=>p.x)))),x1:Math.min(W-1,Math.ceil(Math.max(...pts.map(p=>p.x)))),y0:Math.max(0,Math.floor(Math.min(...pts.map(p=>p.y)))),y1:Math.min(H-1,Math.ceil(Math.max(...pts.map(p=>p.y))))};}
export function inView(p,b){return p.x>=b.x0-1&&p.x<=b.x1+1&&p.y>=b.y0-1&&p.y<=b.y1+1;}
export function focusSector(camera,width,height,sx,sy){camera.zoom=Math.min((width-80)/(SECTOR*56),(height-100)/(SECTOR*28));const x=sx*SECTOR+(SECTOR-1)/2,y=sy*SECTOR+(SECTOR-1)/2;camera.x=width/2-(x-y)*28*camera.zoom;camera.y=height/2-(x+y)*14*camera.zoom;}
const terrainPreviews=new WeakMap();
export function invalidateOverview(map){terrainPreviews.delete(map.terrain||map.map);}
function groundPreview(map,seen){const terrain=map.terrain||map.map;let cached=terrainPreviews.get(terrain);const count=seen?seen.size:-1;if(cached?.count===count&&cached.seen===seen)return cached.canvas;const canvas=document.createElement('canvas');canvas.width=480;canvas.height=240;const c=canvas.getContext('2d'),draw=(x,y)=>{const t=terrain[y]?.[x];if(!t||['yard','ground-grass','void'].includes(t))return;c.fillStyle=t==='water'?'#4c8ca8':t==='bridge'?'#e1bc77':t==='ground-asphalt'?'#313d3f':['floor','ground-concrete','ground-tiles'].includes(t)?'#a39c7e':'#978663';c.fillRect(239+x-y,(x+y)/2,2,1);};if(seen){for(const k of seen){const [x,y,z=0]=k.split(',').map(Number);if(!z)draw(x,y);}}else for(let y=0;y<H;y++)for(let x=0;x<W;x++)draw(x,y);terrainPreviews.set(terrain,{count,seen,canvas});return canvas;}
export function sectorOverview(ctx,project,map,z,seen=null,background=true){if(background)for(let sy=0;sy<10;sy++)for(let sx=0;sx<10;sx++){const x=sx*SECTOR-.5,y=sy*SECTOR-.5,pts=[[x,y],[x+SECTOR,y],[x+SECTOR,y+SECTOR],[x,y+SECTOR]].map(([x,y])=>project(x,y));ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=z?'#33443e':(sx+sy)%2?'#526044':'#5c684b';ctx.fill();ctx.strokeStyle='#9b9d7266';ctx.stroke();}
 if(!z){const top=project(-.5,-.5),left=project(-.5,H-.5),right=project(W-.5,-.5),bottom=project(W-.5,H-.5);ctx.drawImage(groundPreview(map,seen),left.x,top.y,right.x-left.x,bottom.y-top.y);}
 if(z)for(const [k,t]of Object.entries(map.upper[z-1])){const [x,y]=k.split(',').map(Number);if(seen&&!seen.has(k+','+z))continue;const p=project(x,y);ctx.fillStyle=t==='crate'?'#be985c':'#aea47e';ctx.fillRect(p.x-1,p.y-1,2,2);}
}
